Improve the docker setup following Alex's comments

diff --git a/provision/setup-docker b/provision/setup-docker
--- a/provision/setup-docker
+++ b/provision/setup-docker
@@ -4,26 +4,30 @@ set -ex
 COMPOSE_VERSION=1.22.0
 
 if [ ! -z $DOCKER_LARGE_DISK ]; then
+    DOCKER_LIB=/var/lib/docker
+    DOCKER_LIB_LARGE="${DOCKER_LARGE_DISK}/docker/var-lib-docker"
     if [ ! -d $DOCKER_LARGE_DISK ]; then
         echo "Expected a directory at $DOCKER_LARGE_DISK"
         exit 1
     fi
 
-    VAR_LIB_DOCKER="${DOCKER_LARGE_DISK}/docker/var-lib-docker"
-    if [ -d $DOCKER_LARGE_DISK/docker/var-lib-docker ]; then
-        echo "Docker large disk already configured"
-        exit 0
-    fi
-
-    if [ -d /var/lib/docker ]; then
-        echo "Docker is already configured - can't move it at this point"
+    if [ -L $DOCKER_LIB ]; then
+        if [ $(readlink $DOCKER_LIB) = $DOCKER_LIB_LARGE ]; then
+            echo "Docker large disk already configured"
+        else
+            echo "Docker large disk pointing to unexpected location"
+            exit 1
+        fi
+    elif [ -d $DOCKER_LIB ]; then
+        echo "Docker already configured - can't move it at this point"
         exit 1
+    else
+        echo "Configuring docker to use $DOCKER_LIB_LARGE"
+        # The big docker directory is $DOCKER_LIB - we'll move that
+        # out onto the external disk:
+        mkdir -p "$DOCKER_LIB_LARGE"
+        ln -s "$DOCKER_LIB_LARGE" $DOCKER_LIB
     fi
-
-    # The big docker directory is /var/lib/docker - we'll move that
-    # out onto the external disk:
-    mkdir -p "$VAR_LIB_DOCKER"
-    ln -s "$VAR_LIB_DOCKER" /var/lib/docker
 fi
 
 if which -a docker > /dev/null; then
