Refactor of the montagu-machine code
This moves the provisioning code (and therefore necessarily the
Vagrantfile) to the top level of the repo, so that we can use
these scripts to provision physical machines as well as virtual.

The systemctl bits move into their own directory but remain essentially
unchanged

Some renames are simply dropping '.sh' extensions

Alternative approach, but same content, as #1

diff --git a/provision/setup-docker b/provision/setup-docker
--- a/provision/setup-docker
+++ b/provision/setup-docker
@@ -1,16 +1,34 @@
 #!/usr/bin/env bash
-set -x
+set -ex
 
-COMPOSE_VERSION=1.17.0
+COMPOSE_VERSION=1.22.0
+
+if [ ! -z $DOCKER_LARGE_DISK ]; then
+    if [ ! -d $DOCKER_LARGE_DISK ]; then
+        echo "Expected a directory at $DOCKER_LARGE_DISK"
+        exit 1
+    fi
+
+    VAR_LIB_DOCKER="${DOCKER_LARGE_DISK}/docker/var-lib-docker"
+    if [ -d $DOCKER_LARGE_DISK/docker/var-lib-docker ]; then
+        echo "Docker large disk already configured"
+        exit 0
+    fi
+
+    if [ -d /var/lib/docker ]; then
+        echo "Docker is already configured - can't move it at this point"
+        exit 1
+    fi
+
+    # The big docker directory is /var/lib/docker - we'll move that
+    # out onto the external disk:
+    mkdir -p "$VAR_LIB_DOCKER"
+    ln -s "$VAR_LIB_DOCKER" /var/lib/docker
+fi
 
 if which -a docker > /dev/null; then
     echo "docker is already installed"
 else
-    # The big docker directory is /var/lib/docker - we'll move that
-    # out onto the external disk:
-    mkdir -p /mnt/data/docker/var-lib-docker
-    ln -s /mnt/data/docker/var-lib-docker /var/lib/docker
-
     echo "installing docker"
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     sudo add-apt-repository \
@@ -19,7 +37,9 @@ else
    stable"
     sudo apt-get update
     sudo apt-get install -y docker-ce
-    sudo usermod -aG docker vagrant
+    for u in "$@"; do
+        sudo usermod -aG docker "$u"
+    done
 fi
 
 if which -a docker-compose > /dev/null; then
